In [2]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

# Original 3x3 image
image = np.array([[50, 120, 200],
                  [80, 150, 250],
                  [30, 100, 180]], dtype=np.uint8)

interpolated_image_lf = cv2.resize(image, (6, 6), interpolation=cv2.INTER_LINEAR)

# Print both arrays
print("Original 3x3 Image:")
print(image)
print("\n6x6 Interpolated Image:")
print(interpolated_image_lf)

Original 3x3 Image:
[[ 50 120 200]
 [ 80 150 250]
 [ 30 100 180]]

6x6 Interpolated Image:
[[ 50  67 102 140 180 200]
 [ 58  75 110 149 191 213]
 [ 73  90 125 166 214 238]
 [ 68  85 120 161 209 233]
 [ 43  60  95 134 176 198]
 [ 30  47  82 120 160 180]]


In [3]:
import numpy as np
import cv2  

def manual_bilinear_resize(image, Hout, Wout):
    Hin, Win = image.shape
    manually_interpolated_image = np.zeros((Hout, Wout), dtype=image.dtype)

    for i in range(Hout):
        for j in range(Wout):
            # Step-1
            x = (j + 0.5) * Win / Wout - 0.5
            y = (i + 0.5) * Hin / Hout - 0.5
            
			# Step-2
            x0 = int(np.floor(x))
            y0 = int(np.floor(y))
            x1 = min(x0 + 1, Win - 1)
            y1 = min(y0 + 1, Hin - 1)
            
			# Step-3
            x0 = max(x0, 0)
            y0 = max(y0, 0)
            
			# Step-4
            dx = x - x0
            dy = y - y0
            
            A = image[y0, x0]
            B = image[y0, x1]
            C = image[y1, x0]
            D = image[y1, x1]
            
			# Horizontal interpolation
            Top = A * (1 - dx) + B * dx
            Bottom = C * (1 - dx) + D * dx
            
			# Vertical interpolation
            value = Top * (1 - dy) + Bottom * dy

            manually_interpolated_image[i, j] = int(value)

    return manually_interpolated_image


Hout = 6
Wout = 6

manually_interpolated_image = manual_bilinear_resize(image, Hout, Wout)

print("Original 3x3 Image:")
print(image,'\n')
print("Manually_interpolated_image")
print(interpolated_image_lf-manually_interpolated_image)

Original 3x3 Image:
[[ 50 120 200]
 [ 80 150 250]
 [ 30 100 180]] 

Manually_interpolated_image
[[0 0 0 0 0 0]
 [1 0 0 1 0 1]
 [1 0 0 0 1 1]
 [1 0 0 0 1 1]
 [1 0 0 1 0 1]
 [0 0 0 0 0 0]]
